[build]
  command = """
    bash ./netlify-setup.sh &&
    GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" \
      git submodule update --init --remote &&
    mv '_notes/999 - Cache/附件'/* . &&
    jekyll build --trace
  """
  publish = "_site"
